version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "8000:8000"  
    volumes:
      - ./backend:/app
      - /app/node_modules 

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "5173:5173"  
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    depends_on:
      - backend  
    