version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "8000:8000"  
    volumes:
      - ./backend:/app 
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"  
    volumes:
      - ./frontend:/app
      - /app/node_modules   
    depends_on:
      - backend  
    